Feature/675 remove release date where possible
Gepardec/mega-backend pull request #12
Opened 2023-08-31 12:24 UTC by PaulProemer

2023-09-01 11:56 UTC, Ollitod requested changes
**perform rebase onto main** and implement change requests as described in specific comments

2023-09-01 11:56 UTC, Ollitod commented on src/main/java/com/gepardec/mega/service/impl/MonthlyReportServiceImpl.java
> +            monthlyReport = MonthlyReport.builder()
Method buildMonthlyReport never returns null, so the null check can be removed and the result can be returned immediately

2023-09-01 11:56 UTC, Ollitod commented on src/test/java/com/gepardec/mega/rest/WorkerResourceTest.java
> +
remove

2023-09-01 11:56 UTC, Ollitod commented on src/test/java/com/gepardec/mega/rest/WorkerResourceTest.java
> +public class WorkerResourceTest {
JUnit 5 does not require public test class and methods, make class and all methods package-private

2023-09-01 11:56 UTC, Ollitod commented on src/test/java/com/gepardec/mega/rest/WorkerResourceTest.java
Make all fields package-private, since IDE is confused about them not being instantiated explicitly

2023-09-01 11:56 UTC, Ollitod commented on src/test/java/com/gepardec/mega/service/impl/monthlyreport/MonthlyReportServiceImplTest.java
> +
Make all fields package-private, since IDE is confused about them not being instantiated explicitly

2023-09-01 11:56 UTC, Ollitod commented on src/test/java/com/gepardec/mega/service/impl/monthlyreport/MonthlyReportServiceImplTest.java
> +
make all test methods package-private

2023-09-01 11:56 UTC, Ollitod commented on src/test/java/com/gepardec/mega/service/impl/monthlyreport/MonthlyReportServiceImplTest.java
>      @Test
Move to end of class

2023-09-04 10:29 UTC, fhochleitner approved these changes

2023-09-04 10:57 UTC, closed without merging