Feature/684 PrematureEmployeeCheck
Gepardec/mega-backend pull request #25
Opened 2023-11-22 07:26 UTC by LeitnerMi

**Prerequisites: Always create two feature branches (frontend + backend) even if your feature only affects one of them**

**DEV:**
> Development
- [ ] Acceptance tests by dev [OpenShift feature environment]
  - [ ] Moved to "Ready for review"

> Review
- [ ] Pull-request reviewed + approved (including Code Coverage) by reviewer [GitHub]
- [ ] Inform dev after review through MEGA-PR (by reviewer) [Chat Space]
- [ ] Version upgrade by dev [GitHub Issue Milestone + maven revision]
- [ ] Merge to main by dev [GitHub]
  - [ ]  Re-add SNAPSHOT to version and push on main [maven revision]
  - [ ]  Make sure all feature branches are deleted [frontend + backend]
  - [ ]  Moved to "Ready for deployment"

> Deployment
- [ ] Integration and Unit tests on main environment passed [Workflow]
- [ ] Deployed to the test environment [GitOps Workflow triggered]
  - [ ] Moved to "Ready for testing"

**PO:**
> Testing
- [ ] Acceptance tests on the test enviroment passed
- [ ] Inspected and approved
  - [ ] Moved to "Ready for release"

2023-11-24 12:14 UTC, Ollitod requested changes
see comments

2023-11-24 12:14 UTC, Ollitod commented on src/main/resources/db/changelog-premature.yaml
> +      id: 1700130995809-5
do not use generated number

2023-11-24 12:14 UTC, Ollitod commented on src/test/java/com/gepardec/mega/db/repository/PrematureEmployeeCheckRepositoryTest.java
> +import static org.assertj.core.api.AssertionsForClassTypes.assertThat;
import static org.assertj.core.api.Assertions.assertThat; (check other places)

2023-11-24 12:14 UTC, Ollitod commented on src/test/java/com/gepardec/mega/db/repository/PrematureEmployeeCheckRepositoryTest.java
> +    public void addPrematureEmployeeCheck_RETURN_DB_ID() {
methodName_StateUnderTest_ExpectedResult (all places)

2023-11-24 12:14 UTC, Ollitod commented on src/test/java/com/gepardec/mega/db/repository/PrematureEmployeeCheckRepositoryTest.java
> +        persistUser();
declare given, when, then (all places)

2023-11-24 12:14 UTC, Ollitod commented on src/test/java/com/gepardec/mega/service/impl/mapper/PrematureEmployeeCheckMapperTest.java
> +        assertAll(
SoftAssertions.assertSoftly(softly -> {softly.assertThat(xxxx); ...}) (check all places)

2023-11-24 12:14 UTC, Ollitod commented on src/test/java/com/gepardec/mega/service/impl/mapper/PrematureEmployeeCheckMapperTest.java
> +                () -> assertThat(prematureEmployeeCheck.getId()).isEqualTo(1L),
add .as("description")

2023-11-28 14:45 UTC, LeitnerMi commented on src/test/java/com/gepardec/mega/service/impl/mapper/PrematureEmployeeCheckMapperTest.java
> +        assertAll(
71x Usages im Projekt. Soll ich die neuen Refactoren? Soll ich alle Refactoren? Soll ichs lassen, damit nicht 2 Varianten im Code sind? @Ollitod

2023-12-05 08:08 UTC, LeitnerMi commented on src/test/java/com/gepardec/mega/service/impl/mapper/PrematureEmployeeCheckMapperTest.java
> +        assertAll(
Es gibt nur eine  einzige Usage von SoftAssertions

2023-12-14 06:21 UTC, Ollitod approved these changes

2023-12-14 06:21 UTC, merged