Chore/rmlombok
Gepardec/mega-backend pull request #32
Opened 2024-01-22 11:12 UTC by fhochleitner

Oida Oli, ich bin zu blöd für das PR-Template: 

- lombok ist überall entfernt (was bis davor im main-Branch war) 
- unit tests laufen durch 
- integration-tests (postman) laufen durch

Build-Info: 
https://workflows.play.run.gepardec.com/workflows/mega-backend-cicd/mega-backend-build-chore-rmlombok-pmwzd

2024-01-26 06:34 UTC, Ollitod requested changes
Bitte die angemerkten Punkte überall ausbessern

2024-01-26 06:34 UTC, Ollitod commented on src/main/java/com/gepardec/mega/db/entity/employee/StepEntry.java
> +import jakarta.persistence.*;
Vorige Woche ham ma noch geredet :P

2024-01-26 06:34 UTC, Ollitod commented on src/main/java/com/gepardec/mega/domain/model/Comment.java
> +    public Comment(Long id, String message, String authorEmail, String authorName, String updateDate, EmployeeState state, SourceSystem sourceSystem) {
Annotation für AllArgsConstructor war zwar angegeben, aber wird glücklicherweise nicht verwendet. Sollte grundsätzlich nicht mit Builder kombiniert werden (gilt für alle Stellen, wo das so ist)

2024-01-26 06:34 UTC, Ollitod commented on src/main/java/com/gepardec/mega/domain/model/Comment.java
> +    public static final class CommentBuilder {
Da es sich um eine innere Klasse handelt, steht der Klassenname bei Referenzen oder Returnwerten immer dabei, würde ich daher auf "Builder" reduzieren (an allen Stellen)

2024-01-26 06:34 UTC, Ollitod commented on src/main/java/com/gepardec/mega/domain/model/Comment.java
> +
Alle Setter entfernen (gilt für alle Stellen, wo obige Bedinungen erfüllt sind - immutability)

2024-01-26 06:34 UTC, Ollitod commented on src/main/java/com/gepardec/mega/domain/model/Comment.java
> +
Alle Properties final machen -> Builder sollte immutable Objekte erzeugen

2024-01-26 06:34 UTC, Ollitod commented on src/main/java/com/gepardec/mega/domain/model/Comment.java
> +
Visibility auf private, damit Objekte nur über den Builder erzeugt werden können.

2024-01-26 06:34 UTC, Ollitod commented on src/main/java/com/gepardec/mega/domain/model/Comment.java
>  }
Objekterzeugung an private Comment(Builder builder) delegieren und dort Properties direkt zuweisen

2024-01-26 06:34 UTC, Ollitod commented on src/main/java/com/gepardec/mega/domain/model/Comment.java
>  }
Visibility auf private und als Argument einen Builder übergeben (siehe Erklärung bei build())

2024-01-26 06:37 UTC, Ollitod commented on src/main/java/com/gepardec/mega/domain/model/User.java
> +    public User() {
Visibility auf private und als Argument einen Builder übergeben (siehe Erklärung bei build())

2024-01-26 06:37 UTC, fhochleitner commented on src/main/java/com/gepardec/mega/db/entity/employee/StepEntry.java
> +import jakarta.persistence.*;
heast, ich hab aber auch intellij schon seit jahren nicht mehr offen gehabt und bei 40+ klassen nicht gschaut, was da automatisch rauskommt ;-) 

ich ändert mal deinen wünschen entsprechend um, weil ich ja nicht so bin und gib's dir dann zum re-review

2024-01-26 06:39 UTC, Ollitod commented on src/main/java/com/gepardec/mega/domain/model/Comment.java
>      private Long id;
Alle Properties final machen -> Builder sollte nur immutable Objekte erzeugen

2024-01-26 06:40 UTC, Ollitod commented on src/main/java/com/gepardec/mega/domain/model/Comment.java
> +    public Comment() {
Visibility auf private, damit Objekte nur über den Builder erzeugt werden können.

2024-01-26 06:43 UTC, Ollitod commented on src/main/java/com/gepardec/mega/domain/model/Comment.java
> +        }
Kann man sich theoretisch sparen, da in der Top-Level class schon einer erzeugt wird.

2024-02-02 09:47 UTC, Ollitod approved these changes

2024-02-02 10:54 UTC, merged