Feature/721 gildenlead und pl darstellen
Gepardec/mega-backend pull request #35
Opened 2024-02-27 13:26 UTC by sgartner03

**Prerequisites: Always create two feature branches (frontend + backend) even if your feature only affects one of them**

**DEV:**
> Development
- [ ] Acceptance tests by dev [OpenShift feature environment]
  - [ ] Moved to "Ready for review"

> Review
- [ ] Pull-request reviewed + approved (including Code Coverage) by reviewer [GitHub]
- [ ] Inform dev after review through MEGA-PR (by reviewer) [Chat Space]
- [ ] Version upgrade by dev [GitHub Issue Milestone + maven revision]
- [ ] Merge to main by dev [GitHub]
  - [ ]  Re-add SNAPSHOT to version and push on main [maven revision]
  - [ ]  Make sure all feature branches are deleted [frontend + backend]
  - [ ]  Moved to "Ready for deployment"

> Deployment
- [ ] Integration and Unit tests on main environment passed [Workflow]
- [ ] Deployed to the test environment [GitOps Workflow triggered]
  - [ ] Moved to "Ready for testing"

**PO:**
> Testing
- [ ] Acceptance tests on the test enviroment passed
- [ ] Inspected and approved
  - [ ] Moved to "Ready for release"

2024-02-27 15:32 UTC, Ollitod requested changes

2024-02-27 15:32 UTC, Ollitod commented on src/main/java/com/gepardec/mega/personio/employees/PersonioEmployeesServiceImpl.java
> +    }
Besser wärs wenn du z.B. eine Klasse "PersonioMitarbeiterInfo" erstellst, welche die beiden Attribute beinhaltet und dann machst du nur einen Schnittstellenaufruf und befülllst die beiden Attribute des Objekts.

2024-03-01 06:40 UTC, Ollitod requested changes
Schaut grundsätzlich super aus, aber schau bitte noch, dass wir aus unserer Domain das Dto (PersonioEmployee) rausbekommen. Also am besten die aktuelle Klasse auf PersonioEmployeeDto umbenennen und eine neue Klasse PersonioEmployee bei den Domain-Models anlegen + Mapper implementieren.

2024-03-05 07:12 UTC, Ollitod requested changes

2024-03-05 10:01 UTC, sgartner03 commented on src/main/java/com/gepardec/mega/personio/employees/PersonioEmployeeDto.java
danke, das mit den gettern hat echt keinen sinn gemacht...

2024-03-05 10:24 UTC, sgartner03 commented on src/main/java/com/gepardec/mega/personio/employees/PersonioEmployeesServiceImpl.java
> +    DomainMapper<PersonioEmployee, PersonioEmployeeDto> mapper;
Darf ich  fragen, was der Vorteil ist?
Ich dachte, bei sowas ist der möglichst abstrakteste Typ zu wählen - was spricht hier dagegen? :)

2024-03-05 10:54 UTC, sgartner03 commented on src/main/java/com/gepardec/mega/personio/employees/PersonioEmployeeDto.java
Nach den Changes bekomme ich folgende Fehlermeldung: 
```
 jakarta.ws.rs.ProcessingException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "first_name" (class com.gepardec.mega.personio.employees.PersonioEmployeeDto$Builder), not marked as ignorable (9 known properties: "absenceEntitlement", "lastName", "personalnummer", "internalProjectLead", "id", "email", "vacationDayBalance", "guildLead", "firstName"])
```
das @JsonProperty auf dem Feld beim Builder behebt den Fehler

2024-03-05 22:48 UTC, Ollitod commented on src/main/java/com/gepardec/mega/personio/employees/PersonioEmployeesServiceImpl.java
> +    DomainMapper<PersonioEmployee, PersonioEmployeeDto> mapper;
Im Prinzip eigentlich lediglich die verbesserte Leserlichkeit. Anscheinend kommt CDI sogar damit klar. IntelliJ gibt allerdings eine Warning aus, dass der Injection Point nicht eindeutig ist. Anscheinend ist das aber eine falsche Warning, da es ja auch mit deiner Variante funktioniert hat.

2024-03-05 23:02 UTC, Ollitod commented on src/main/java/com/gepardec/mega/personio/employees/PersonioEmployeeDto.java
Du hast völlig recht, ich hab das anscheinend noch mit einem Codestand getestet... ups xD

2024-03-05 23:06 UTC, Ollitod approved these changes

2024-03-07 07:58 UTC, merged